const cpp = {
  cppTutorialSidebar: [
    {
      type: 'category',
      label: 'C++ Tutorials',
      collapsed: false,
      items: [
        'cpp-home',
        'c++/cpp-learning-roadmap',
        {
          type: 'category',
          label: 'Basic',
          collapsed: true,
          items: [
            'c++/basic/index',
            'c++/basic/intro',
            'c++/basic/variables-and-types',
            'c++/basic/operators',
            'c++/basic/control-flow',
            'c++/basic/functions',
            'c++/basic/pointers',
            'c++/basic/references',
            'c++/basic/cpp_tutorial_with_cmake',
            'c++/basic/opp-cpp',
            'c++/basic/binary_hexadecimal',
            'c++/basic/c++_compilers',
          ],
        },
        {
          type: 'category',
          label: 'Intermediate',
          collapsed: true,
          items: [
            'c++/intermediate/index',
            'c++/intermediate/intro',
            'c++/intermediate/classes-and-objects',
            'c++/intermediate/constructors-and-destructors',
            'c++/intermediate/inheritance',
          ],
        },
        {
          type: 'category',
          label: 'Advanced',
          collapsed: true,
          items: [
            'c++/advanced/error-handling',
            'c++/advanced/raii-deep-dive',
            'c++/advanced/design-patterns',
            'c++/advanced/memory-model-and-atomics',
            'c++/advanced/template-metaprogramming',
            'c++/advanced/coroutines',
            'c++/advanced/modules',
            'c++/advanced/debugging-strategies',
            'c++/advanced/performance-profiling',
            'c++/advanced/best-practices',
            'c++/advanced/index',
            'c++/advanced/polymorphism',
            'c++/advanced/templates',
            'c++/advanced/stl-intro',
            'c++/advanced/vectors-and-maps',
            'c++/advanced/sorting-and-searching',
            'c++/advanced/smart-pointers',
            'c++/advanced/move-semantics',
            'c++/advanced/custom-allocators',
            'c++/advanced/threads',
            'c++/advanced/mutexes-and-locking',
            'c++/advanced/async-and-futures',
          ],
        },
        {
          type: 'category',
          label: 'Expert',
          collapsed: true,
          items: [
            'c++/expert/index',
            'c++/expert/file-io',
            'c++/expert/sockets',
            'c++/expert/posix',
            'c++/expert/concepts-and-ranges',
            'c++/expert/sfinae',
            'c++/expert/constexpr',
            'c++/expert/conan',
            'c++/expert/interview-prep',
          ],
        },
        {
          type: 'category',
          label: 'Projects',
          collapsed: true,
          items: [
            'c++/projects/index',
            'c++/projects/books',
            'c++/projects/docs',
            'c++/projects/tools',
            'c++/projects/gdb',
            'c++/projects/valgrind',
            'c++/projects/testing',
            'c++/projects/googletest',
            'c++/projects/catch2',
            'c++/projects/open-source',
          ],
        },
        {
          type: 'category',
          label: 'Resources',
          collapsed: true,
          items: [
            'c++/resources/index',
            'c++/resources/books',
            'c++/resources/docs',
            'c++/resources/tools',
            'c++/resources/gdb',
            'c++/resources/valgrind',
            'c++/resources/testing',
            'c++/resources/googletest',
            'c++/resources/catch2',
            'c++/resources/open-source',
          ],
        },
        {
          type: 'category',
          label: 'Standard (C++ Versions)',
          collapsed: true,
          items: [
            'c++/standard/index',
            'c++/standard/intro',
            'c++/standard/C++11',
            'c++/standard/c++14',
            'c++/standard/c++17',
            'c++/standard/c++23',
          ],
        },
      ],
    },
  ],
};

module.exports = cpp;
